# Generated by Django 4.2 on 2023-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('locations', models.TextField()),
                ('minPrice', models.IntegerField()),
                ('maxPrice', models.IntegerField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Korepetycje',
        ),
    ]
