# Generated by Django 4.2 on 2023-04-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_offert_delete_korepetycje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='link',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='maxPrice',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='minPrice',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='subject',
        ),
    ]
