# Generated by Django 4.2 on 2023-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_offert_description_remove_offert_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='link',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offert',
            name='locations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='maxPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='minPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
